services:
    postgres:
        image: 'postgres:15.2-alpine'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: my-local-db
        ports:
            - '5432:5432'
    redis:
        image: 'redis:7.0-alpine'
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data
volumes:
    postgres_data:
    redis_data:
